on:
  pull_request:
    types: [unlabeled]
name: Clean up
env:
  CLUSTER_REPO: dudo/k8s_colors
jobs:
  tear_down:
    name: Tear down feature branch
    runs-on: ubuntu-latest
    steps:
    - name: Kustomized Namespace - Cleanup Overlay
      env:
        TOKEN: ${{ secrets.TOKEN }}
      uses: zyngl/cleanup_kustomized_namespace@v0.9.1
      with:
        args: --flux
