on: pull_request
name: Clean up
jobs:
  tear_down:
    name: Tear down feature branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'closed'
    - name: git commit cleanup overlay
      uses: actions/kustomized-namespace-cleanup-overlay@v0.9.0
      env:
        CLUSTER_REPO: ${{ secrets.CLUSTER_REPO }}
        TOKEN: ${{ secrets.TOKEN }}
