# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: pull_request
name: Build, push, and deploy
jobs:
  docker:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && contains( github.event.pull_request.labels, 'deploy' )
    steps:
    - uses: actions/checkout@master
    - name: docker login
      uses: actions/docker/login@313deac5bd89b2114c8d6dd264e6baad00be374f
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: docker build
      uses: actions/docker/cli@313deac5bd89b2114c8d6dd264e6baad00be374f
      env:
        SERVICE: ${{ secrets.SERVICE }}
      with:
        args: build -t $SERVICE .
    - name: docker tag
      uses: actions/docker/tag@313deac5bd89b2114c8d6dd264e6baad00be374f
      env:
        SERVICE: ${{ secrets.SERVICE }}
        TARGET_IMAGE: ${{ secrets.TARGET_IMAGE }}
      with:
        args: $SERVICE $TARGET_IMAGE
    - name: docker push sha
      uses: actions/docker/cli@313deac5bd89b2114c8d6dd264e6baad00be374f
      env:
        TARGET_IMAGE: ${{ secrets.TARGET_IMAGE }}
      with:
        args: push $TARGET_IMAGE:$IMAGE_SHA
  deploy:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - uses: actions/checkout@master
    - name: git commit create overlay
      uses: actions/kustomized-namespace-create-overlay@v0.9.0
      env:
        CLUSTER_REPO: ${{ secrets.CLUSTER_REPO }}
        SERVICE: ${{ secrets.SERVICE }}
        TARGET_IMAGE: ${{ secrets.TARGET_IMAGE }}
        TOKEN: ${{ secrets.TOKEN }}
